"use client";

import Link from "next/link";
import { use, useEffect, useState } from "react";
import { getOverview } from "../lib/api";
import { useAppState } from "../lib/app-state";
import type { OverviewInsight, OverviewMetric, OverviewResponse, Workspace } from "../lib/types";

const titles: Record<Workspace,string>={overview:"Executive overview",explore:"Explore the business",insights:"What needs attention",ask:"Ask your analyst",actions:"Recommended actions",reports:"Executive reports"};
function slug(value:string):Workspace|null{return ["overview","explore","insights","ask","actions","reports"].includes(value)?value as Workspace:null;}

export default function WorkspaceView({params}:{params:Promise<{workspace:string}>}){const{state}=useAppState();const workspace=slug(use(params).workspace)??"overview";const dataset=state.dataset;if(!dataset)return <div className="empty-state"><span className="empty-icon">↑</span><h1>Upload your business data</h1><p>Start with a CSV or Excel file. The analyst will only expose analyses supported by validated fields.</p></div>;return <><div className="hero-row"><div><span className="eyebrow">{dataset.business_model_label??"Business dataset"}</span><h1>{titles[workspace]}</h1><p>Grounded in <strong>{dataset.file_name}</strong>. No fabricated numbers or unsupported metrics.</p></div><div className="confidence-card"><span>Data readiness</span><strong>{dataset.quality_issues===0?"Ready":`${dataset.quality_issues} issue${dataset.quality_issues===1?"":"s"}`}</strong><small>{Math.round(dataset.business_model_confidence*100)}% model confidence</small></div></div>{workspace==="overview"?<Overview datasetId={dataset.dataset_id}/>:<Placeholder workspace={workspace}/>}</>}

function Overview({datasetId}:{datasetId:string}){const[data,setData]=useState<OverviewResponse|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);useEffect(()=>{let alive=true;setLoading(true);setError(null);getOverview(datasetId).then(r=>alive&&setData(r)).catch(e=>alive&&setError(e instanceof Error?e.message:"Overview could not be loaded.")).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[datasetId]);if(loading)return <OverviewSkeleton/>;if(error)return <div className="panel overview-error" role="alert"><span className="eyebrow">OVERVIEW UNAVAILABLE</span><h2>We couldn't calculate the executive overview.</h2><p>{error}</p><p>No substitute figures are shown.</p></div>;if(!data)return null;return <div className="executive-overview"><div className="overview-intro"><div><span className="eyebrow">EXECUTIVE SNAPSHOT · {data.scope_label.toUpperCase()}</span><h2>{data.headline}</h2><p>{data.subheadline}</p></div><div className="source-badge"><span>Source of truth</span><strong>Uploaded data</strong></div></div><section className="metric-grid">{data.metrics.map(m=><MetricCard key={m.id} metric={m}/>)}</section><section className="decision-grid"><article className="panel decision-panel"><SectionHeading eyebrow="WHAT CHANGED" title="Recent movement" kicker="Deterministic"/>{data.what_changed.length?<ul className="signal-list">{data.what_changed.map((x,i)=><li key={`${x}-${i}`}>{x}</li>)}</ul>:<EmptySignal text="No comparable period or snapshot was available in the uploaded data."/>}</article><article className="panel decision-panel"><SectionHeading eyebrow="WHAT NEEDS ATTENTION" title={data.attention.length?`${data.attention.length} priority signal${data.attention.length===1?"":"s"}:`+"":"No high-priority signal"} kicker="Evidence-backed"/>{data.attention.length?<div className="insight-stack">{data.attention.map(i=><InsightCard key={i.id} insight={i} kind="attention"/>)}</div>:<EmptySignal text="No validated risk threshold was triggered in the current scope."/>}</article></section><section className="panel opportunity-panel"><div className="section-heading"><div><span className="eyebrow">OPPORTUNITIES & PERFORMANCE</span><h3>Where to focus next</h3></div><Link href="/dashboard/explore" className="text-link">Explore →</Link></div>{data.opportunities.length?<div className="opportunity-grid">{data.opportunities.map(i=><InsightCard key={i.id} insight={i} kind="opportunity"/>)}</div>:<EmptySignal text="No validated opportunity signal is available yet. The analyst will not invent one to fill the space."/>}</section><section className="overview-footer-note"><span>Every value above is calculated from the current dataset and scope.</span><span>Evidence is available on each insight.</span></section></div>}

function SectionHeading({eyebrow,title,kicker}:{eyebrow:string;title:string;kicker:string}){return <div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h3>{title}</h3></div><span className="section-kicker">{kicker}</span></div>}
function MetricCard({metric}:{metric:OverviewMetric}){return <article className={`metric-card ${metric.tone}`}><div className="metric-topline"><span className="eyebrow">{metric.label}</span>{metric.delta_pct!==null&&metric.delta_pct!==undefined&&<span className={`delta ${metric.delta_pct>=0?"up":"down"}`}>{metric.delta_pct>=0?"↑":"↓"} {Math.abs(metric.delta_pct).toFixed(1)}%</span>}</div><strong>{metric.display_value}</strong>{metric.delta_label&&<span className="metric-subtext">{metric.delta_label}</span>}</article>}
function InsightCard({insight,kind}:{insight:OverviewInsight;kind:"attention"|"opportunity"}){return <div className={`insight-card ${kind} ${insight.severity}`}><div className="insight-main"><div className="insight-marker" aria-hidden="true"/><div><div className="insight-title-row"><strong>{insight.title}</strong><span>{insight.severity}</span></div><p>{insight.summary}</p></div></div><details><summary>Why this matters & evidence</summary><div className="evidence-box"><p><strong>Why:</strong> {insight.why_it_matters}</p><p><strong>Recommended action:</strong> {insight.recommendation}</p><p><strong>Calculation:</strong> {insight.evidence.calculation}</p><p><strong>Scope:</strong> {insight.evidence.scope}</p><p><strong>Source fields:</strong> {insight.evidence.source_fields.join(", ")||"Validated dataset"}</p></div></details></div>}
function EmptySignal({text}:{text:string}){return <div className="empty-signal">{text}</div>}
function OverviewSkeleton(){return <div className="overview-grid-skeleton"><div className="skeleton-hero"/><div className="skeleton-row"><div/><div/><div/></div><div className="skeleton-wide"/></div>}
function Placeholder({workspace}:{workspace:Workspace}){return <div className="placeholder panel"><span className="eyebrow">V4 WORKSPACE</span><h2>{titles[workspace]}</h2><p>This workspace uses the same dataset context as the executive overview. Its analytical experience will build on the same evidence model rather than creating a separate source of truth.</p><div className="trust-note">Numbers will appear only after deterministic analytics are available.</div></div>}
